// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'usernotice.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserNotice _$UserNoticeFromJson(Map<String, dynamic> json) => UserNotice(
      json['uid'] as int,
      json['unread_comment'] as int,
      json['read_commentindex'] as int,
      json['unread_reply'] as int,
      json['read_replyindex'] as int,
      json['unread_sysnotice'] as int,
      json['read_sysnoticeindex'] as int,
      json['unread_member'] as int,
      json['read_member'] as int,
      json['unread_follow'] as int,
      json['read_follow'] as int,
      json['unevaluate_activity'] as int,
      json['evaluate_activity'] as int,
      json['unread_evaluate'] as int,
      json['read_evaluate'] as int,
      json['unread_evaluatereply'] as int,
      json['read_evaluatereply'] as int,
      json['unread_friend'] as int,
      json['read_friend'] as int,
      json['isUserUpdate'] as int,
      json['unread_shared'] as int,
      json['read_shared'] as int,
      json['unread_orderpending'] as int,
      json['unread_orderfinish'] as int,
      json['unread_actlike'] as int,
      json['read_actlike'] as int,
      json['unread_commentlike'] as int,
      json['read_commentlike'] as int,
      json['unread_evaluatelike'] as int,
      json['read_evaluatelike'] as int,
      json['unread_buglike'] as int,
      json['read_buglike'] as int,
      json['unread_suggestlike'] as int,
      json['read_suggestlike'] as int,
      json['unread_bugcomment'] as int,
      json['read_bugcomment'] as int,
      json['unread_suggestcomment'] as int,
      json['read_suggestcomment'] as int,
      json['unread_bugreply'] as int,
      json['read_bugreply'] as int,
      json['unread_suggestreply'] as int,
      json['read_suggestreply'] as int,
      json['unread_bugcommentlike'] as int,
      json['read_bugcommentlike'] as int,
      json['unread_suggestcommentlike'] as int,
      json['read_suggestcommentlike'] as int,
      json['unread_gpmsg'] as int,
      json['read_gpmsg'] as int,
      json['unread_communitymsg'] as int,
      json['read_communitymsg'] as int,
      json['unread_singlemsg'] as int,
      json['read_singlemsg'] as int,
      json['unread_goodpricecomment'] as int,
      json['read_goodpricecommentindex'] as int,
      json['unread_goodpricereply'] as int,
      json['read_goodpricereplyindex'] as int,
      json['unread_goodpricecommentlike'] as int,
      json['read_goodpricecommentlike'] as int,
      json['order_expiration'] as int,
      json['unread_momentlike'] as int,
      json['read_momentlike'] as int,
      json['unread_momentcomment'] as int,
      json['read_momentcomment'] as int,
      json['unread_momentreply'] as int,
      json['read_mementreply'] as int,
      json['unread_momentcommentlike'] as int,
      json['read_momentcommentlike'] as int,
    );

Map<String, dynamic> _$UserNoticeToJson(UserNotice instance) =>
    <String, dynamic>{
      'uid': instance.uid,
      'unread_comment': instance.unread_comment,
      'read_commentindex': instance.read_commentindex,
      'unread_reply': instance.unread_reply,
      'read_replyindex': instance.read_replyindex,
      'unread_sysnotice': instance.unread_sysnotice,
      'read_sysnoticeindex': instance.read_sysnoticeindex,
      'unread_member': instance.unread_member,
      'read_member': instance.read_member,
      'unread_follow': instance.unread_follow,
      'read_follow': instance.read_follow,
      'unevaluate_activity': instance.unevaluate_activity,
      'evaluate_activity': instance.evaluate_activity,
      'unread_evaluate': instance.unread_evaluate,
      'read_evaluate': instance.read_evaluate,
      'unread_evaluatereply': instance.unread_evaluatereply,
      'read_evaluatereply': instance.read_evaluatereply,
      'unread_friend': instance.unread_friend,
      'read_friend': instance.read_friend,
      'isUserUpdate': instance.isUserUpdate,
      'unread_shared': instance.unread_shared,
      'read_shared': instance.read_shared,
      'unread_orderpending': instance.unread_orderpending,
      'unread_orderfinish': instance.unread_orderfinish,
      'unread_actlike': instance.unread_actlike,
      'read_actlike': instance.read_actlike,
      'unread_commentlike': instance.unread_commentlike,
      'read_commentlike': instance.read_commentlike,
      'unread_evaluatelike': instance.unread_evaluatelike,
      'read_evaluatelike': instance.read_evaluatelike,
      'unread_buglike': instance.unread_buglike,
      'read_buglike': instance.read_buglike,
      'unread_suggestlike': instance.unread_suggestlike,
      'read_suggestlike': instance.read_suggestlike,
      'unread_bugcomment': instance.unread_bugcomment,
      'read_bugcomment': instance.read_bugcomment,
      'unread_suggestcomment': instance.unread_suggestcomment,
      'read_suggestcomment': instance.read_suggestcomment,
      'unread_bugreply': instance.unread_bugreply,
      'read_bugreply': instance.read_bugreply,
      'unread_suggestreply': instance.unread_suggestreply,
      'read_suggestreply': instance.read_suggestreply,
      'unread_goodpricecomment': instance.unread_goodpricecomment,
      'read_goodpricecommentindex': instance.read_goodpricecommentindex,
      'unread_goodpricereply': instance.unread_goodpricereply,
      'read_goodpricereplyindex': instance.read_goodpricereplyindex,
      'unread_bugcommentlike': instance.unread_bugcommentlike,
      'read_bugcommentlike': instance.read_bugcommentlike,
      'unread_suggestcommentlike': instance.unread_suggestcommentlike,
      'read_suggestcommentlike': instance.read_suggestcommentlike,
      'unread_goodpricecommentlike': instance.unread_goodpricecommentlike,
      'read_goodpricecommentlike': instance.read_goodpricecommentlike,
      'unread_gpmsg': instance.unread_gpmsg,
      'read_gpmsg': instance.read_gpmsg,
      'unread_communitymsg': instance.unread_communitymsg,
      'read_communitymsg': instance.read_communitymsg,
      'unread_singlemsg': instance.unread_singlemsg,
      'read_singlemsg': instance.read_singlemsg,
      'order_expiration': instance.order_expiration,
      'unread_momentlike': instance.unread_momentlike,
      'read_momentlike': instance.read_momentlike,
      'unread_momentcomment': instance.unread_momentcomment,
      'read_momentcomment': instance.read_momentcomment,
      'unread_momentcommentlike': instance.unread_momentcommentlike,
      'read_momentcommentlike': instance.read_momentcommentlike,
      'unread_momentreply': instance.unread_momentreply,
      'read_mementreply': instance.read_mementreply
    };
