// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

User _$UserFromJson(Map<String, dynamic> json) => User(
      json['uid'] != null ?  json['uid'] as int : 0,
      json['mobile'] != null ? json['mobile'] as String : "",
      json['username'] != null ? json['username']as String : "",
      json['sex'] as String?,
      json['country'] as String?,
      json['province'] as String?,
      json['city'] as String?,
      json['signature'] != null ? json['signature'] as String : "",
      json['profilepicture'] as String?,
      json['pwerrorcount'] as int?,
      json['birthday'] as String?,
      json['followers'] as int?,
      json['following'] as int?,
      json['updatetime'] as String?,
      json['likenum'] as int?,
      json['token'] as String?,
      json['likeact'] as int?,
      json['collectionact'] as int?,
      json['likecomment'] != null ?  json['likecomment'] as int : 0,
      json['likeevaluate'] as int?,
      json['collectionproduct'] as int?,
      json['aliuserid']  != null ? json['aliuserid'] as String : "",
      json['likebug'] != null ?  json['likebug'] as int : 0,
      json['likesuggest'] != null ?  json['likesuggest'] as int : 0,
      json['likebugcomment'] != null ?  json['likebugcomment'] as int : 0,
      json['likesuggestcomment'] != null ?  json['likesuggestcomment'] as int : 0,
      json['likegoodpricecomment'] != null ?  json['likegoodpricecomment'] as int : 0,
      json['notinteresteduids'] as String?,
      json['blacklist'] as String?,
      json['goodpricenotinteresteduids'] as String?,
      json['usertype'] as int?,
      json['interest'] as String?,
      json['voice'] as String?,
      json['isNew'] as bool?,
      json['business'] != null ?  json['business'] as int : 0,
      json['likemoment'] != null ?  json['likemoment'] as int : 0,
      json['likemomentcomment'] != null ?  json['likemomentcomment'] as int : 0,
      json['wxuserid'] != null ?  json['wxuserid'] as String : "",
      json['iosuserid'] != null ?  json['iosuserid'] as String : "",
      json['subject'] != null ?  json['subject'] as String : "",
    );

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'uid': instance.uid,
      'username': instance.username,
      'sex': instance.sex,
      'country': instance.country,
      'province': instance.province,
      'city': instance.city,
      'signature': instance.signature,
      'profilepicture': instance.profilepicture,
      'pwerrorcount': instance.pwerrorcount,
      'birthday': instance.birthday,
      'followers': instance.followers,
      'following': instance.following,
      'isFollow': instance.isFollow,
      'updatetime': instance.updatetime,
      'likenum': instance.likenum,
      'token': instance.token,
      'likeact': instance.likeact,
      'collectionact': instance.collectionact,
      'likecomment': instance.likecomment,
      'likeevaluate': instance.likeevaluate,
      'collectionproduct': instance.collectionproduct,
      'aliuserid': instance.aliuserid,
      'likebug': instance.likebug,
      'likesuggest': instance.likesuggest,
      'likebugcomment': instance.likebugcomment,
      'likesuggestcomment': instance.likesuggestcomment,
      'likegoodpricecomment': instance.likegoodpricecomment,
      'notinteresteduids': instance.notinteresteduids,
      'blacklist': instance.blacklist,
      'goodpricenotinteresteduids': instance.goodpricenotinteresteduids,
      'usertype': instance.usertype,
      'interest': instance.interest,
      'voice': instance.voice,
      'isNew': instance.isNew,
      'business': instance.business,
      'likemoment': instance.likemoment,
      'likemomentcomment': instance.likemomentcomment,
      'mobile': instance.mobile,
      'wxuserid': instance.wxuserid,
      'aliuserid': instance.aliuserid,
      'subject': instance.subject
    };
